class SimpleException extends Exception {}

bool okCatch, okFinally

void func() {
    a := 42
	try {
		throw new SimpleException()
	} catch (SimpleException e) {
		println "Catch"
		okCatch = true
	} finally {
		println "Finally"
		okFinally = true
	}
}

void testFoo() {
    t := 3.14
	func()
	assert(okCatch)
	assert(okFinally)
}

testFoo()
